services:
    nginx:
        build: .
        container_name: nginx-fancy-books
        ports:
            - '9082:80'
        volumes:
            - /media/Apps/Amatur/books:/usr/share/nginx/html
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
